In [2]:
import numpy as np

In [4]:
a= np.array([[0,1,2,3], [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
a.shape

(2, 4)

In [6]:
a[1,3]

7

In [7]:
a[1,2]=8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [8]:
a[0]

array([0, 1, 2, 3])

In [9]:
a[1]

array([4, 5, 8, 7])

In [10]:
b= np.array([3,5])
b

array([3, 5])

Gerando Números Aleatórios

In [11]:
import random

In [12]:
prob= random.random()
print(prob)

0.829619805136324


In [13]:
number= random.randint(1,6)
print(number)

4


In [14]:
import numpy as np

In [15]:
np.random.randint(1,6,(4,6))

array([[5, 4, 1, 2, 1, 1],
       [1, 3, 3, 2, 1, 4],
       [4, 1, 3, 4, 2, 5],
       [1, 5, 5, 3, 2, 5]])